### ISSUE TITLE
Symbology for HAND Layer in HANDProject Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#121]
## Specification
*Project Type*:  `HAND` 
*Layer(s)*: `Height Above Nearest Drainage`
https://github.com/Riverscapes/RiverscapesXML/blob/ba60f1c61d80d17bb5096ff5e3823cc12565107e/RaveBusinessLogic/HAND.xml#L10
*Type(s)* - `Raster`

## Description and/or Explanation of Need
![image](https://user-images.githubusercontent.com/9723905/123515933-c4125780-d656-11eb-8f9e-624d6a2a6a39.png)

## Example(s) of Inspiration
![image](https://user-images.githubusercontent.com/9723905/123516004-2f5c2980-d657-11eb-94d9-d1395b0f3fdd.png)

-------
## To-Do 
- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) - @joewheaton to-do
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] #124
- [x] #125
- [x] #126
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] #127
- [ ] #128
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by joewheaton** [comment]
This is now rolled into TauDEM, so closing.
