### ISSUE TITLE
Master Issue for Confinement Project

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#133]
## Specification
*Project Type*:  `Confinement` 
*Layers in their current form*:

- [ ]  Confinement Raw
- [ ]  Confinement Margins
- [ ]  Confining polygon
- [ ]  Confinement Ratio
- [ ]  Constriction Ratio
- [ ]  Active Channel Buffer
- [ ]  Flowlines
- [ ]  Split Points
- [ ]  Flowline Segments
- [ ]  Error Polylines
- [ ]  Error Polygons

Business Logic for the layers:
https://github.com/Riverscapes/RiverscapesXML/blob/8530418a7f0782ccd188ad931622cd9238454902/RaveBusinessLogic/Confinement.xml#L11-L29

*Type(s)* - Raster and Vector

## Description
This is a master issue for getting the Confinement Project type up and running with coherent symbology and project views on all three platforms. I will convert individual tasks to new issues as I see fit. 

Currently, we have a [confinement tool](http://confinement.riverscapes.xyz/) that calculates *channel* confinement along a stream network (NHD). It takes a valley bottom polygon and tells us where the stream network intersects it. 

![image](https://user-images.githubusercontent.com/73319684/122285607-31cac080-ceac-11eb-9b59-5fcb448400e4.png)Ultimately, it is these confining margins that we are interested in. Where are they? How long are they? Do they occur on both sides of the channel? As the tool stands, this information is displayed and calculated. 

**Moving forward, however, we want to...**

a) more fully take advantage of the additional information being calculated and display it in a useful manner 

b) shift from a focus on channel networks (i.e. single thread systems) toward using channel belts to calculate confinement

c) expose more intermediate steps (such as buffers), along with relevant information (such as resolution)

d) clean up the organization and labeling of RAVE layers.

## Work that's already been done:
Confinement for QRAVE #105 
Confinement for WebRave #107 
-------
_**For each layer**_
- [x] Start new branch with descriptive name for these changes
- [x] Make necessary edits to business logic and commit to new branch 
- [x] #137
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] #138
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] #139
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**_Additionally_**

- [x] #134
  - [x] shouldn't be labeled "confining polygon"
Multiple visualizations: 
    - [x] semi-transparent polygon (change business logic to have the transparency consistent)
    - [x] just an outline (similar to the new VBET display)
- [ ] #135
  - [x] highlight 100% proportion constricted reaches with a thicker line?
  
**labeling**

- [x] change "Confinement Raw" to "Confinement Type"
- [x] change "Confinement Margins" to "Confining Margins"
- [x] change "Constriction Ratio" to "Proportion Constricted" or "Constriction Proportion"
- [x] change "Confining Polygon" to "Valley Bottom Polygon"

**organization**

- [x] #136

  ```
  confinement.gpkg
  		confinement_buffers
  		confinement_ratio
  		confinement_raw
  		confining_margins
  ```

- [ ] change "Confinement_ratio" feature class to "Confinement_Calculations" to more accurately describe the attributes calculated in that table:

  ```
  confinement_ratio
  			fields
  				fid
  				NHDPlusID
  				Confinement_Ratio
  				Constriction_Ratio
  				Approx_Leng
  				Confin_Leng
  				Constr_Leng
  ```

_This issue will be updated with more tasks as they come up_

**Comment by lauren-herbine** [comment]
**Project used:** [Confinement for HUC 10090102](https://data.riverscapes.xyz/#/BLM/40fff861-ca0c-4f33-908d-26094c919a93)

### QRave symbology and business logic
Here is a video showing the symbology and business logic: 

[![Alt text](https://img.youtube.com/vi/-/0.jpg)](https://www.youtube.com/watch?v=VID)

Here are the layers:
![image](https://user-images.githubusercontent.com/73319684/128078247-628dc4ef-b00b-46b1-b282-aad3697cfd18.png)

And this is what the basic project view looks like (Project view: Confinement Ratio by Stream Segment):
![image](https://user-images.githubusercontent.com/73319684/128078902-f6ce2c73-39d8-4500-9098-fee3b82e52d4.png)





### ArcRave symbology and business logic

### WebRave symbology and business logic

**Comment by lauren-herbine** [comment]
In order to properly symbolize "Constriction Proportion" in WebRave, I need a project that displays the full range of possible values. Right now, the only [three projects](https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch) we have for confinement have very very low constriction values across the entire HUC. This is related to [Issue 13](https://github.com/Riverscapes/RiverscapesData/issues/13) in Data. @joewheaton how pressing is it to have confinement symbology and such dialed for WebRave? Looking through some other tickets, it looks like there's a decent amount still broken right now (is this because we have a Channel Area Project now?). It will be tough to finish up the last couple of layers (~3) until we have this run in more diverse HUCs. Thoughts?

**Comment by joewheaton** [comment]
My understanding from @philipbaileynar is that @KellyMWhitehead has started running the 20 HUC 8s for the Mississippi. Those should be looking good. However, I can't remember if they are going to run confinement right now. They could.

There is also a new confinement based on new channel area and VBET in the [Klamath](https://gist.github.com/joewheaton/46c6dca19d1972127cf71df0042bdafa), which you can look at (it looked much better, but still may need some tweaking).

I'd say we need to shift towards taking a closer look at confinement, so use Klamath to help with symbology and then start looking at QC reports for the 20.

**Comment by philipbaileynar** [comment]
No confinement is not finished.
