### ISSUE TITLE
QRAVE Compliance - BRAT

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#145]
## QRAVE Compliance - BRAT

*Project Type*: BRAT
*Layer(s)*: All inputs, outputs & intermediates 
*Type(s)* - Raster & Vector

### Description 

Get BRAT to be QRAVE compliant by authoring .qml and updating business logic as needed.  

-------
## To-Do 

- [x] Start new branch with descriptive name for these changes (QRAVE_BRAT_Curation) 
- [x] #146
- [x] #147
- [x] #149 
- [x] #155
- [x] #156
- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] #192
- [x] #162
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] #194
- [x] After pull request(s) merged, test in updated qRAVE
- [x] Make any necessary changes/updates
- [ ] Make final pull request and test merged changes
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by wally-mac** [comment]
@Cashe93 would I assign this to @Tanmanfalcon while you are on the river or are you going to deal with this when you return?

**Comment by Cashe93** [comment]
I'll deal with this when I return. @Tanmanfalcon will be working on the Riverscapes Context #148

**Comment by joewheaton** [comment]
@Cashe93 just checking in on how this is going.

**Comment by Cashe93** [comment]
@joewheaton, aside from the raster symbology, this is done. Just haven't marked it complete since we still need to figure out what to do with categorical rasters.
