### ISSUE TITLE
QRAVE Compliance - Riverscapes Context

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#148]
## QRAVE Compliance - Riverscapes Context

*Project Type*: RS Context
*Layer(s)*: All folders 
*Type(s)* - Raster & Vector

### Description 

Get RS Context to be QRAVE compliant by authoring .qml and updating business logic as needed.  

-------
## To-Do

- [x] Start new branch with descriptive name for these changes (QRAVE_RSContext_Curation)
- [x] Author *.qml for Transportation layers and test in QRAVE Author *.qml for Hydrology layers and test in QRAVE
- [x] Author *.qml for Climate (PRISM) layers and test in QRAVE
- [x] Author *.qml for Land Management layers and test in QRAVE
- [x] Author *.qml for Topography/Hillshade layers and test in QRAVE
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Author or Update any project type documentation
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Update or Add Project Views to Reflect Changes (if necc.)
- [x] #152
- [x] After pull request(s) merged, test in updated qRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by Tanmanfalcon** [comment]
Here is a [link](https://data.riverscapes.xyz/#/PUBLIC_DATA/ace49f52-d3a9-41f8-8525-04d591f51aa6) to the warehouse project that was used to test layers.

Perennial, Intermittent, Ephemeral Drainage Networks
![qnetworks](https://user-images.githubusercontent.com/79670857/126878980-74d9c31d-685a-4764-9e9e-a494915ba0ad.PNG)

Upstream Drainage Area
![qdrainagearea](https://user-images.githubusercontent.com/79670857/126878987-eeca48a8-f82b-40dc-afe4-4867de3f7a6a.PNG)

Full NHD HR+ Drainage Network
![qfullnetwork](https://user-images.githubusercontent.com/79670857/126878993-e8875e72-70fe-469d-acc8-da412bfa0ddf.PNG)

Drainage Wings
![qdrainagewings](https://user-images.githubusercontent.com/79670857/126878995-7fe275fa-d4b5-40ef-9380-a4610c0a445c.PNG)

River Polygons
![qriverpolygons](https://user-images.githubusercontent.com/79670857/126879001-4cae59e9-2166-4e70-9b41-0e76abf9cbc0.PNG)

Lakes, Ponds, Reservoirs and WaterBodies
![qlakes](https://user-images.githubusercontent.com/79670857/126879004-8c87745f-5e76-49c9-b79e-6f46073f5021.PNG)

Canals and Ditches, and Pipes and Ditches
![qpipesandcanals](https://user-images.githubusercontent.com/79670857/126879012-fad65d49-a427-4f7c-a692-bcc058bd1ef7.PNG)

**Comment by Tanmanfalcon** [comment]
Transportation: Roads and Rail
![qtransportation](https://user-images.githubusercontent.com/79670857/126879340-58c27200-f920-4bcb-8055-89c86d6f94a0.PNG)

**Comment by Tanmanfalcon** [comment]
Climate
Mean Annual Precipitation
![qprecip](https://user-images.githubusercontent.com/79670857/126879551-6863a86c-ae74-4fd6-94ad-b8c4ce6b750c.PNG)

Mean Temperature
![qtemp](https://user-images.githubusercontent.com/79670857/126879554-d1e82e69-fa61-4628-9668-bfa087817439.PNG)

Minimum Temperature
![qmintemp](https://user-images.githubusercontent.com/79670857/126879555-7982875b-192f-4c20-aaeb-7b2f4a0e94c8.PNG)

Maximum Temperature
![qmaxtemp](https://user-images.githubusercontent.com/79670857/126879557-908fed22-87ab-4c3f-923e-09d7a235b8e7.PNG)

Mean Dewpoint Temperature
![qdewpoint](https://user-images.githubusercontent.com/79670857/126879558-2c3b3a05-fedc-48f6-be6b-101c25871315.PNG)

Minimum Vapor Pressure Deficit
![qvaporpressure](https://user-images.githubusercontent.com/79670857/126879560-f01c1570-6f2f-4fde-8e9b-8b13c3ef7ab6.PNG)

**Comment by Tanmanfalcon** [comment]
NHD Flowlines
![qnhdflowlines](https://user-images.githubusercontent.com/79670857/126879727-7a318747-8326-40c4-81f5-e4c05d12ee5d.PNG)

**Comment by Tanmanfalcon** [comment]
Watershed Boundaries
HUC 4
![qhuc4](https://user-images.githubusercontent.com/79670857/126880587-47793069-ba8a-436b-9a43-40661a428404.PNG)

HUC 6
![qhuc6](https://user-images.githubusercontent.com/79670857/126880588-a9aa38f0-a6ee-4cc8-ad2c-172c23498883.PNG)

HUC 8
![qhuc8](https://user-images.githubusercontent.com/79670857/126880590-3afe44ed-a528-482d-b81a-77e9c10559ba.PNG)

HUC 10
![qhuc10](https://user-images.githubusercontent.com/79670857/126880592-cb713bf6-6991-4366-a8fa-bf8b684bdcf5.PNG)

HUC12
![qhuc12](https://user-images.githubusercontent.com/79670857/126880594-14aef5a5-acad-49b4-9d95-2743a4828196.PNG)

**Comment by Tanmanfalcon** [comment]
Land Management
Land Ownership
![qlandownership](https://user-images.githubusercontent.com/79670857/126880603-f979d41a-43cf-4dc6-bc96-9f442d37a3a8.PNG)

Fair Market Value
![qfairmarketvalue](https://user-images.githubusercontent.com/79670857/126880606-edf68932-02f7-49d3-9a3f-ae04e17b4981.PNG)

**Comment by Tanmanfalcon** [comment]
Topography and Derivatives
DEM (10m NED)
![qdem10](https://user-images.githubusercontent.com/79670857/126880642-2936810a-da8c-4ca2-b4a1-0881fc223ce3.PNG)

Slope Analysis
![qslope](https://user-images.githubusercontent.com/79670857/126880646-33f6f99e-f985-43c4-a621-003981afa39a.PNG)

Flow Accumulation
![qflowacc](https://user-images.githubusercontent.com/79670857/126880651-0a113608-c0f3-4e82-a632-a31cd5491425.PNG)

Drainage Area
![qdrainageareatopo](https://user-images.githubusercontent.com/79670857/126880653-d46ce0b4-83ca-4609-9500-834bdab25f55.PNG)

Detrended DEM (HAND - Height Above Nearest Drainage)
![qHAND](https://user-images.githubusercontent.com/79670857/126880655-58b43515-030c-4ace-af4a-a9cf2d5c8087.PNG)

DEM Hillshade
![qhillshade](https://user-images.githubusercontent.com/79670857/126880659-63947271-bb21-4bcb-b575-5af1a4252274.PNG)

**Comment by wally-mac** [comment]
@Tanmanfalcon these look great. Let me go through each of these in more detail tomorrow and provide you with some more feedback. Nice work!

**Comment by joewheaton** [comment]
> NHD Flowlines
> ![qnhdflowlines](https://user-images.githubusercontent.com/79670857/126879727-7a318747-8326-40c4-81f5-e4c05d12ee5d.PNG)

It might be nice to not say "NHD Flowlines", but "Estimated Bankfull Width (m)"

**Comment by joewheaton** [comment]
> Land Management
> Land Ownership
> ![qlandownership](https://user-images.githubusercontent.com/79670857/126880603-f979d41a-43cf-4dc6-bc96-9f442d37a3a8.PNG)
> 
This is consistent with what we are doing in ArcGIS @Tanmanfalcon. However, I don't like the NPS being yellow. Maybe a darker Green? Look at some other things like Google Maps and OpenStreet Maps for ideas? Once we agree, lets put this over also into Arc...

**Comment by joewheaton** [comment]
Thanks for all this @Tanmanfalcon , especially the screen shots. Please make sure to include hillshades behind your raster layer screen shots in the background as this is how they will be typically viewed (for future ones... don't redo these).

**Comment by Tanmanfalcon** [comment]
> > NHD Flowlines
> > ![qnhdflowlines](https://user-images.githubusercontent.com/79670857/126879727-7a318747-8326-40c4-81f5-e4c05d12ee5d.PNG)
> 
> It might be nice to not say "NHD Flowlines", but "Estimated Bankfull Width (m)"

@joewheaton QGIS will not keep the name of the layer if I change it and export it as a QML. I suppose this is a Business Logic fix? Since I am unfamiliar with Business Logic, is there a way I can change the name of the layer in Business Logic so that the layer opens the layer with the same name each time?

**Comment by Tanmanfalcon** [comment]
@joewheaton Here is updated screenshots of the Estimated Bankfull Width flowlines as well as the land ownership with an updated color for the National Park lands. Most maps I researched appear to label National Parks as a darker green. Is this a color you like?
![qland_ownership2](https://user-images.githubusercontent.com/79670857/127221030-64e132e7-07a6-425a-aeef-b99472c2c061.PNG)

![qbankfull_2](https://user-images.githubusercontent.com/79670857/127221052-7551c9f8-e958-41fc-a902-7175293fbdd8.PNG)

**Comment by Tanmanfalcon** [comment]
The QMLs for the Ecoregions have been completed. They look exactly as they do in Arcmap (see pictures below). I could not make a legend that contained all of the symbols, so youll just have to trust me that they are all exactly as they are in Arcmap. The vegetation qml's have also been created. Since Q is unable to read Raster Attribute Tables, all we can really do is create the symbology qml's and wait on Q to have a feature to read attribute tables. But the symbology is ready to go. 

Ecoregion 2
![qecoregions2](https://user-images.githubusercontent.com/79670857/128079364-9694a2d1-61f1-46f0-b20a-9290deea75e0.PNG)

Ecoregion 3 symbology (same as Arcmap)
![qecoregions3](https://user-images.githubusercontent.com/79670857/128079369-2d882863-c415-4489-a302-b06609e4111c.PNG)

Existing Vegetation symbology (thanks to SLYR tool)
![qexistingveg](https://user-images.githubusercontent.com/79670857/128079376-99e566a1-75c7-4f3d-aeab-390e6eee8d95.PNG)

**Comment by joewheaton** [comment]
Thanks @Tanmanfalcon
