### ISSUE TITLE
Symbology for ChannelArea Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#166]
## Specification
*Project Type*:  `ChannelArea` 
*Layer(s)*:
Everything

*Type(s)* - Raster and Vector

## Description and/or Explanation of Need
We now have a new ChannelArea project   type from #151 (see [here ](https://github.com/Riverscapes/RiverscapesXML/blob/ChannelArea/RaveBusinessLogic/ChannelArea.xml)for auto-generated, uncurated business logic). Use [this project from MHFD](https://data.riverscapes.xyz/#/Anabranch/7e367e76-f8d7-439c-be33-d4a05ab941ae) to get started.

Please expose all the layers. For those with NHD as inputs (not always the case), we should display them based on FCode (see [FCODEs ticket here](https://github.com/Riverscapes/riverscapes-tools/issues/347)). For the output, it may make sense to have a hollow one (for viewing with aerial imagery) and a transparent blue fill one (sort of how we have hollow and fill for VBET).

-------
## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] #338
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] #390
- [x] Update or Add Project Views to Reflect Changes (if necc.)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] After pull request(s) merged, test in updated ArcRAVE
- [x] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by MattReimer** [comment]
Just FYI @lauren-herbine  there's a;ready a pull request and a branch for this `ChannelArea` complete with a template business logic xml

https://github.com/Riverscapes/RiverscapesXML/pull/151

**Comment by lauren-herbine** [comment]
Thanks @MattReimer!

**Comment by lauren-herbine** [comment]
@joewheaton when you say you want the inputs broken out by FCodes do you mean something like:

```
<Node label="Inputs" xpath="Inputs">
        <Children>
          <Node label="Artificial Path (55800)" xpath="Geopackage/Layers/Vector[@id=...
          <Node label="Canal/Ditch (33600)" xpath="Geopackage/Layers/Vector[@id=...
          <Node label="Connector (33400)" xpath="Geopackage/Layers/Vector[@id=....
          <Node label="Stream/River (4600)" xpath="Geopackage/Layers/Vector[@id=...
          <Node label="Intermittent (46003)" xpath="Raster[@id=...
          <Node label="Perennial (46006)" xpath="Raster[@id=...
        </Children>
      </Node>
```
...etc.

OR

something more similar to how we have it exposed currently?:

```
<Node label="Inputs" xpath="Inputs">
        <Children>
          <Node label="NHD Flowlines" xpath="Geopackage/Layers/Vector[@id=...
          <Node label="NHD Flow Areas" xpath="Geopackage/Layers/Vector[@id=...
          <Node label="NHD Waterbody Areas" xpath="Geopackage/Layers/Vector[@id=....
        </Children>
      </Node>

**Comment by joewheaton** [comment]
Good question @lauren-herbine. I don't know yet. See https://github.com/Riverscapes/RiverscapesData/discussions/7 for some of where we're going with ChannelArea. So for now, what you have will work for the NHD use case. I am not sure what to do or how to handle these other use cases. Run with this, and when we get resolution on how we handle the custom use cases, we'll revise it.

**Comment by lauren-herbine** [comment]
Moving some documentation over to this ticket from #151 .

**Project used:** [Channel Area for HUC 10190005](https://data.riverscapes.xyz/#/Anabranch/7e367e76-f8d7-439c-be33-d4a05ab941ae)

### QRave symbology and business logic
Here is a video showing the symbology and business logic- felt more efficient than 15+ screenshots: 

[![Alt text](https://img.youtube.com/vi/WFfosaufVNA/0.jpg)](https://www.youtube.com/watch?v=VID)

And here are the layers:
![image](https://user-images.githubusercontent.com/73319684/127922326-d95357f4-0882-403b-ad30-abfee70eef9b.png)

And this is what the basic project view looks like (hollow and filled polygons turned on):
![image](https://user-images.githubusercontent.com/73319684/127922451-a717217c-ab7a-4748-8697-3b4efe75b25a.png)




### ArcRave symbology and business logic

### WebRave symbology and business logic

**Comment by joewheaton** [comment]
Other than documentation, this is done.
