### ISSUE TITLE
Symbology for TauDEM Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#167]
## Specification
*Project Type*:  `TauDEM` 
*Layer(s)*:
Everything

*Type(s)* - 
Both Raster or Vector

## Description and/or Explanation of Need
- We now have a new TauDEM project type from [here](https://github.com/Riverscapes/riverscapes-tools/issues/340) (see [here](https://github.com/Riverscapes/RiverscapesXML/blob/taudemBL/RaveBusinessLogic/TauDEM.xml) for auto-generated, uncurated business logic). 
- Use [this project from MHFD](https://data.riverscapes.xyz/#/Anabranch/448e792e-4873-4467-bdea-dd8ea5c57803) to get started.
- Since the TauDEM projects basically are replacing the HAND projects, please take the symbology and business logic from [`HAND.xml`](https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/HAND.xml) as a start to get this working. 
- Please expose all the layers and organize logically as inputs, intermediates and outputs.

## Example(s) of Inspiration

Please pull some of Tarboton's [TauDEM](https://hydrology.usu.edu/taudem/taudem5/documentation.html) papers for better understanding and inspiration for labels, units, range of expected values (or categories) and symbology. Post questions you have (with screen shots) if they arise. 

-------
## To-Do 
- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [x] #214
- [x] #215
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] #250
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] Update or Add Project Views to Reflect Changes (if necc.)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] After pull request(s) merged, test in updated ArcRAVE
- [x] After pull request(s) merged, test in updated WebRAVE
- [x] Delete local branch(es) you used for your pull request(s)

**Comment by MattReimer** [comment]
Just FYI @shelbysawyer  there's already a branch for this `taudemBL` and a pull request all set in draft mode:

https://github.com/Riverscapes/RiverscapesXML/pull/154

This includes a template businesslogic xml.

**Comment by shelbysawyer** [comment]
Ah! Thanks @MattReimer, that's helpful.

**Comment by shelbysawyer** [comment]
@MattReimer @joewheaton I've got the layers organized they way I want them, but I've run into an issue with exposing them properly. For example, `Channel Area` is showing up under Inputs, but `DEM` and `DEM Hillshade` are not. This same issue is happening with Intermediates and Outputs. I _think_ it's a problem in the way that I've written the path in the BL, but I'm not sure how to confirm the path beyond looking at the project XML.

Here is how the current TOC looks with my BL:
<img width="224" alt="toc" src="https://user-images.githubusercontent.com/73311751/127929053-628967e9-00e0-4078-a167-546311fcacfb.PNG">

**Comment by MattReimer** [comment]
Hey @shelbysawyer let me take a crack at this.

What you have in your project XML is:

```xml
<?xml version="1.0"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/Projects/XSD/V1/TauDEM.xsd">
  <Name>TauDEM project for HUC 10190005</Name>
  <ProjectType>TauDEM</ProjectType>
  <!-- ... Stuff -->
  <Realizations>
    <TauDEM id="TauDEM" dateCreated="2021-07-28T12:09:43.389286" guid="5db29142-efd7-11eb-9039-4ccc6a258976" productVersion="0.0.1">
      <Name>TauDEM project for HUC 10190005</Name>
      <Inputs>
        <Raster guid="0a4bd9b3-bb96-4391-8cd7-74d28bd2d84a" id="DEM">
          <Name>DEM</Name>
          <Path>inputs\dem.tif</Path>
        </Raster>
        <Raster guid="6dee938d-b4ae-4f30-83af-125bcb060431" id="HILLSHADE">
          <Name>DEM Hillshade</Name>
          <Path>inputs\dem_hillshade.tif</Path>
        </Raster>
<!-- etc... -->
```

so in xpath-speak those **absolute** xpaths are:

```
Realizations/TauDEM/Inputs/Raster[@id='DEM']
Realizations/TauDEM/Inputs/Raster[@id='HILLSHADE']
```

Let me know if this part doesn't make sense. Xpaths can be a little tricky but if you get this the rest is easy.

Our business logic allows us to use _relative_ xpaths so we don't need to constantly put the full path everywhere

From your business logic:

``` xml
<Node xpathlabel="Name" xpath="Realizations/TauDEM">
  <!-- 
  NOTE: xpath="Realizations/TauDEM" means Everything inside this node
   happens in the conext of "Realizations/TauDEM"
   -->
  <Children collapsed="false">
     <Node label="Inputs" xpath="Inputs">
      <!-- NOTE: xpath="Inputs" means our context becomes extended further to:
         "Realizations/TauDEM/Inputs"
      -->
      <Children collapsed="true">
      <!-- 
        Now, instead of using the full path of:
              "Realizations/TauDEM/Inputs/Raster[@id='DEM']"
        
        we can just use:
              "Raster[@id='DEM']"
      -->
        <Node label="DEM" xpath="Raster[@id='DEM']" type="raster" symbology="dem" transparency="40" id="dem" />
        <Node xpathlabel="DEM Hillshade" xpath="Raster[@id='HILLSHADE']" type="raster" symbology="" id="hillshade" />
        <Node label="Channel Area" xpath="Geopackage/Layers/Vector[@id='CHANNEL_AREA']" type="polygon" id="channel_area" symbology="ChannelArea" />
      </Children>

```

**Comment by shelbysawyer** [comment]
Thank you @MattReimer! I'm going to give this a try!

**Comment by shelbysawyer** [comment]
@MattReimer Oops, just realized I'm still working in the taudemBL branch for these last couple commits.. should I make a new branch and make these same changes again? Can I do another pull request under the same branch name? Sorry!

**Comment by joewheaton** [comment]
> > Please pull some of Tarboton's TauDEM papers for better understanding and inspiration for labels, units, range of expected values (or categories) and symbology. Post questions you have (with screen shots) if they arise.
> 
> @joewheaton I'm wondering if I'm missing something.. I opened up all of the publications and documentation on his site, and didn't see any examples of the TauDEM intermediates (Pitfill, D-Inf Flow Directions, D-Inf Contributing Area, D-Inf Flow Directions Slope) symbolized. The best I could do was slide 27 in the ppt I've attached below.

@shelbysawyer here is the original paper (nothing inspiring for cartography): https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=3510&context=cee_facpub

You should just make up your own.

**Comment by shelbysawyer** [comment]
@joewheaton That's what I ended up doing. Waiting to hear back about the branch situation I started (oops) and then you'll be able to see / respond to the symbology I chose for each.

**Comment by joewheaton** [comment]
@shelbysawyer this is looking great for QRAVE. We need to follow through and get this done for ArcRAVE and WebRAVE. I updated due date.

**Comment by shelbysawyer** [comment]
@joewheaton @MattReimer Getting ArcRAVE going on this and realizing that the business logic is now broken for TauDEM in some places (for example, the hillshade is now not coming through because it has been moved from inputs to intermediates in the project xml). I'm wondering if I missed some changes? I'm wondering if, in the future, when changes are made to the project structure that are likely to break the business logic, we could create a linked "to-do" to check the business logic?

**Comment by MattReimer** [comment]
@shelbysawyer yes. We're so used to working in a vacuum that we forget there's downstream consequences. When the XML changes there should be some sort of heads-up for the businesslogic folks

@KellyMWhitehead, @philipbaileynar and myself should keep this in mind.

**Comment by shelbysawyer** [comment]
I'm struggling with translating the color ramps I made in QRAVE for TWI and D∞ Contributing Area into ramps that work the same way in ArcRAVE. In QRAVE, it allows you to stretch over a ramp but force color breaks at certain values. I can't figure out how to make this work in ArcRAVE. As a result, I ended up categorizing them and it honestly looks terrible. How have we dealt with this in the past? @Cashe93 Any tips or ideas here?

**Comment by Cashe93** [comment]
Hey @shelbysawyer, unfortunately I haven't dealt with this specifically. My suggestion would be to classify the raster and bin it accordingly, but it looks like you've already tried that. Would you be able to share a screenshot of the classified settings and resulting symbology when you try this in ArcRAVE?

**Comment by shelbysawyer** [comment]
@Cashe93 Yes-- working with it again now, but I might end up posting here. Part of the problem is that when I get the symbology to behave the way I want, the layer's "legend" looks terrible.

**Comment by shelbysawyer** [comment]
Closing this because curation of TauDEM is done. Documentation has not been finished and is tracked [here](https://github.com/Riverscapes/riverscapes-tools/issues/495).
