### ISSUE TITLE
Symbology for xxxxx Layer in yyyy Project Type

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#197]
## WebRave Compliance - BRAT

*Project Type*: BRAT
*Layer(s)*: All inputs, outputs & intermediates 
*Type(s)* - Raster & Vector

### Description 

Get BRAT to be WebRAVE compliant by authoring .qml and updating business logic as needed.  

-------
## To-Do 

- [x] Start new branch with descriptive name for these changes (WebRAVE_BRAT_Curation) 
- [x] Successfully author a vector layer for WebRAVE
- [ ] Successfully author a raster layer for WebRAVE

**Comment by Cashe93** [comment]
@MattReimer could you point me in the direction of the WebRAVE symbology curation documentation?

**Comment by MattReimer** [comment]
Sure! We're still arguing where this documentation should live but

https://github.com/Riverscapes/RiverscapesXML/blob/master/docs/Symbology/webRAVERasters.md
https://github.com/Riverscapes/RiverscapesXML/blob/master/docs/Symbology/webRAVEVectors.md

The Vectors are probably going to be a bit of a learning curve if you haven't used Mapbox Studio before. Happy to chat about it if you get stuck.

**Comment by Cashe93** [comment]
@MattReimer you were indeed correct. I got stuck fairly early on when trying to attempt Vectors. I got to step 4 of creating a JSON file. For somebody who hasn't used Mapbox before, I find the instructions to be quite vague. Is there a video tutorial or something else that we can reference? 

![image](https://user-images.githubusercontent.com/49880208/131233941-724bd421-c757-4543-a02e-3656d548a3b1.png)

**Comment by MattReimer** [comment]
Yeah, sorry. the docs aren't good because we don't want to have to re-document Mapbox

The docs for mapbox studio are pretty thorough:
https://docs.mapbox.com/studio-manual/guides/

but it's a pretty different process from QGIS and Arcmap. Have another go and if you get stuck on something I have some time this week and we can slog through it together if you'd like.

**Comment by Cashe93** [comment]
@MattReimer, would you have time for a short meeting today about this? I've symbolized everything in Mapbox and exported the .json file, I'm just having trouble figuring out the next steps.

**Comment by MattReimer** [comment]
@Cashe93 I don't have any headspace for WebRAVE today. Can we circle back to this after the long weekend? We can do it first thing on tuesday.

**Comment by Cashe93** [comment]
No worries, @MattReimer. Tuesday works great!

**Comment by Cashe93** [comment]
@MattReimer or @philipbaileynar  would you have time to do quick meeting about this today? I just want to make sure that the work I'm doing is on the right track. I will be available between 12:30 and 3 or anytime after 4. Thanks!

**Comment by MattReimer** [comment]
Yeah no problem @Cashe93 I'll send you a meeting invite

**Comment by Cashe93** [comment]
Thanks, @MattReimer!

**Comment by Cashe93** [comment]
@MattReimer, there is a layer that I'm trying to symbolize for BRAT that symbolizes null values. In Mapbox it won't let symbolize a 'no value' (makes me select 0). I looked at some stack exchange stuff for JSON and found that the best way to return a null is with '{ }'. Is the following line correct for symbolizing nulls? Or is there another way this can be done for webrave?
```
["==", ["get", "Orig_DA"], {}]

```

**Comment by MattReimer** [comment]
Try `null`. It should be supported in the JSON. you might need to enter it manually though

**Comment by Cashe93** [comment]
Sounds good. I've changed it to the following. 
```
 ["==", ["get", "Orig_DA"], null]
```

**Comment by Cashe93** [comment]
@MattReimer, it looks like the legend is working, but the symbology is not being applied to the network. 

![image](https://user-images.githubusercontent.com/49880208/133909094-12d50495-f841-4f4b-90e7-5db6d5df53e4.png)

Here is what the JSON file looks like:

```
{
  "$schema": "https://xml.riverscapes.xyz/Symbology/web/vector.schema.json",
  "legend": [
    ["hsl(0, 100%, 48%)", "None: 0 dams"],
    ["hsl(40, 100%, 50%)", "Rare: 0-1 dams/km (0-2 dams/mi)"],
    ["hsl(60, 100%, 48%)","Occasional:  1-5 dams/km (2-8 dams/mi)"],
    ["hsl(100, 99%, 45%)","Frequent: 5-15 dams/km (8-24 dams/mi)"],
    ["hsl(216, 100%, 45%)","Pervasive: 15-40 dams/km (24-64 dams/mi)"]
  ],
  "layerStyles": [
    {
      "id": "Existing Dam Capacity ",
      "type": "line",
      "source": "composite",
      "source-layer": "oCC_EX-bmdfb2",
      "minzoom": 11,
      "layout": {},
      "paint": {
          "line-width": 1.25,
          "line-color": [
              "step",
              ["get", "oCC_EX"],
              "hsl(0, 100%, 48%)",
              0.000001,
              "hsl(40, 100%, 50%)",
              1,
              "hsl(40, 100%, 50%)",
              1.000001,
              "hsl(60, 100%, 48%)",
              5,
              "hsl(60, 100%, 48%)",
              5.000001,
              "hsl(100, 99%, 45%)",
              15,
              "hsl(100, 99%, 45%)",
              15.000001,
              "hsl(216, 100%, 45%)",
              31,
              "hsl(216, 100%, 45%)"
          ]
      }
  }
  ]
}
```

**Comment by MattReimer** [comment]
I'm on the case. Leave it with me. I'll let you know if there's something that affects any further symbologies but it's probably a bug on my end

**Comment by MattReimer** [comment]
We should be ready to finish this off. @Cashe93 it's in your court.

**Comment by MattReimer** [comment]
Hey @Cashe93. 

### Couple of preliminary things:

1. **Links please**: Please always drop a link for the address of what you're seeing so I don't have to go hunt it down. Also when you do screenshots can you not crop them so much. Sometimes the context of what's around them is kind of important for debugging. Better to include the whole window and then mark it up with text/arrows or pointers to what the problem is.
2. **Arc/Q/Web**:If you download a project off the staging server you should be able to open it in Q, Arc and WebRAVE simultaneously. You can do that either by going to "Project Info" in webrave and clicking the download button or jumping back to the staging warehouse and doing it that way.
3. **More sample projects:** I've thrown a few more projects in the processing Queue. They should start popping up in a few hours if there are no errors.

### Ok now the issues:

I'll be using this project for reference so we can see apples-to-apples:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/59f4ef1e-1076-4c54-8029-087767f1f8a5

> 1. Vegetation suitability raster node empty

The Vegetation suitability rasters missing is from the intermediates right? (I can't tell since the screenshot only shows the one folder). That's likely a business logic problem to do with an xpath not being found or something similar. If it shows up properly in Q we might have an issue so let me know.

> 3. Layer displays but symbology not working (shows up as black) for all outputs

I suspect that it's targeting the wrong field attribute or something. Can you check that the name in the webRAVE json is the same as the one QGIS is looking for?

> Existing and Historic Riparian raster symbology not displaying.

This is likely a mismatched symbology name problem if it's in both Q and Web. Take a look at the RSContext.xml business logic and just copy whatever that is using.

> Node exists but layer not displaying for nearly all intermediates

I actually see `Existing Dam Capacity` but it's so faint that the lines blend into the hillshade.

**Comment by Cashe93** [comment]
Thanks! Also,  I've looked into these issues a bit more and it appears that the projects themselves have erroneous outputs. For each of the three BRAT Projects that can be found on the staging server [here](https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch), the attributes for all outputs and a handful of intermediates are 'null'. [See this brief video](https://vimeo.com/635536417).

**Comment by MattReimer** [comment]
aaaaaaaand fail again. Kelly hooked me up with some untested fixes though so third time's the charm. Kicking it off again...

**Comment by joewheaton** [comment]
I think this is done. Re open @MattReimer or @Cashe93 if not.
