### ISSUE TITLE
RCA QRAVE Curation 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#202]
Get RCA to be QRAVE compliant by authoring .qml and updating business logic as needed.  

-------
## To-Do 

- [x] Start new branch with descriptive name for these changes (QRAVE_RCA_Curation) 
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ]
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] Make any necessary changes/updates
- [ ] Make final pull request and test merged changes
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by Cashe93** [comment]
@joewheaton, does an RCA project.xml exist so that I can test out layers?

**Comment by joewheaton** [comment]
Do you mean RCAT (which I see they were calling RCA)? I think we have two tasks here, but I'm going to ask @wally-mac and @philipbaileynar to clarify.
1. We need to ingest existing [RCAT](http://rcat.riverscapes.xyz) runs the lab has produced as pyRCAT runs and those will get a similar treatment to what you're doing with @MattReimer on pyBRAT. Hopefully not too different as RCAT was authored by Jordan as well so should look real familiar. 
2. We need to author RVD business logic for both pyRVD and sqlRVD. @philipbaileynar started on making production-grade RCA, by just tackling [RVD ](https://github.com/Riverscapes/riverscapes-tools/tree/master/packages/rvd )first. 


I found on Box:

-  some old [RCAT and RCA Documentation](https://usu.box.com/s/g5zk74ir1j1eidnyfuafgxhb5nqgsf1x) done in the CHaMP days
- A bunch of our [Network Tool outputs by HUC 8 for Columbia River Basin](https://usu.box.com/s/5laj4b4o9qj5g8thk6j9vllylltksnw4) in `Box\0_ET_AL\Projects\USA\CHaMP\Analysis_Tools\Network_Tools_BY_HUC8\`. Therein ,  I went to `Lochsa_17060303` and found
  - `[RVD(1.0.8)`](https://usu.box.com/s/yx5f95hzgwxcryagplup5pq0stewiyw0)
  -  `[RCA(1.0.8)`](https://usu.box.com/s/y6t4vwgorwd8ejec9n13k52qcbpx3ip5)

The good news is even on those old 1.08 versions of RCA and RVD (see[ here for releases](https://github.com/Riverscapes/RCAT/releases) that extend up to 2.0.3) is that  we have pretty good `project.rs.xml`.  

## Examples of pyRCA and py RVD `project.rs.xml`
### RCA
```
<?xml version="1.0" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/Program/master/Project/XSD/V1/Project.xsd">
	<Name>Et_Al_Lochsa_RCA</Name>
	<ProjectType>RCA</ProjectType>
	<MetaData>
		<Meta name="HUCID">17060303</Meta>
		<Meta name="Region">CRB</Meta>
		<Meta name="Watershed">Lochsa</Meta>
	</MetaData>
	<Inputs>
		<Raster guid="F44A55AE-C98D-4DCE-88F3-32C3962E2D73" id="EXCOV1">
			<Name>Existing Cover</Name>
			<Path>01_Inputs/01_Ex_Cov/Ex_Cov_1/US_140EVT/us_140evt_Clip.tif</Path>
		</Raster>
		<Raster guid="9828BED9-D197-4764-9A31-894E5670E4F2" id="HISTCOV1">
			<Name>Historic Cover</Name>
			<Path>01_Inputs/02_Hist_Cov/Hist_Cov_1/US_140BPS/us_140bps_Clip.tif</Path>
		</Raster>
		<Vector guid="A8D0CDAD-0592-4C82-B16F-E7FC24F2D515" id="NETWORK1">
			<Name>Segmented Network</Name>
			<Path>01_Inputs/03_Network/Network_1/NHD_24k_17060303_Perennial_500m.shp</Path>
		</Vector>
		<Vector guid="51CF2A4E-5506-4AB7-9D1F-BCFE70D5F96A" id="VALLEY1">
			<Name>Fragmented Valley Bottom</Name>
			<Path>01_Inputs/04_Frag_Valley/Frag_Valley_1/17060303_FP_Connectivity.shp</Path>
		</Vector>
		<Vector guid="17D44D10-51E2-4451-9FD9-C032C63FB626" id="LRP1">
			<Name>Large River Polygon</Name>
			<Path>01_Inputs/05_LRP/LRP_1/NHD_Area.shp</Path>
		</Vector>
	</Inputs>
	<Realizations>
		<RCA dateCreated="2017-07-18 11:53:16" guid="30CC3957-7225-4ABF-8B9D-B13C19CA7ACA" id="RZ1" productVersion="1.0.8" promoted="True">
			<Name>RCA Realization 1</Name>
			<Parameters>
				<Param name="width_thresh">120</Param>
			</Parameters>
			<Inputs>
				<ExistingVegetation ref="EXCOV1">
					<ExistingRasters>
						<Raster guid="D39CD01F-157C-41DE-A9D6-3C78AEB3491F">
							<Name>Existing Riparian</Name>
							<Path>01_Inputs/01_Ex_Cov/Ex_Cov_1/Ex_Rasters/Ex_Riparian.tif</Path>
						</Raster>
						<Raster guid="421015CA-F7F3-44DA-B02C-8D7B57182269">
							<Name>Existing Vegetation Cover</Name>
							<Path>01_Inputs/01_Ex_Cov/Ex_Cov_1/Ex_Rasters/Ex_Veg_Cover.tif</Path>
						</Raster>
						<Raster guid="9B290A1C-E5D6-4203-80A7-04076158B8F8">
							<Name>Land Use Intensity</Name>
							<Path>01_Inputs/01_Ex_Cov/Ex_Cov_1/Ex_Rasters/Land_Use_Intensity.tif</Path>
						</Raster>
					</ExistingRasters>
				</ExistingVegetation>
				<HistoricVegetation ref="HISTCOV1">
					<HistoricRasters>
						<Raster guid="D6E5EC3C-5ADB-4809-BB1D-73B573BE7118">
							<Name>Historic Riparian</Name>
							<Path>01_Inputs/02_Hist_Cov/Hist_Cov_1/Hist_Rasters/Hist_Riparian.tif</Path>
						</Raster>
						<Raster guid="085E703B-FB2A-4119-9E37-41FF2B1ECD4D">
							<Name>Historic Vegetation Cover</Name>
							<Path>/Hist_Rasters/Hist_Veg_Cover.tif</Path>
						</Raster>
					</HistoricRasters>
				</HistoricVegetation>
				<DrainageNetworks>
					<Network ref="NETWORK1">
						<ThiessenPolygons guid="7B4254E1-27A0-4C84-A011-816EF947C254">
							<Name>Thiessen Polygons</Name>
							<Path>/Thiessen/Thiessen_Valley.shp</Path>
						</ThiessenPolygons>
					</Network>
				</DrainageNetworks>
				<FragmentedValleyBottom ref="VALLEY1"/>
				<LargeRiverPolygon ref="LRP1"/>
			</Inputs>
			<Analyses>
				<Analysis>
					<Name>RCA Analysis</Name>
					<Outputs>
						<Vector guid="998DD458-90AD-453F-92F9-93D8E9D80E15">
							<Name>RCA</Name>
							<Path>02_Analyses/Output_1/17060303_RCA_120.shp</Path>
						</Vector>
					</Outputs>
				</Analysis>
			</Analyses>
		</RCA>
	</Realizations>
</Project>

```

### RVD
```
<?xml version="1.0" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/Program/master/Project/XSD/V1/Project.xsd">
	<Name>Et_Al_Lochsa_RVD</Name>
	<ProjectType>RVD</ProjectType>
	<MetaData>
		<Meta name="HUCID">17060303</Meta>
		<Meta name="Region">CRB</Meta>
		<Meta name="Watershed">Lochsa</Meta>
	</MetaData>
	<Inputs>
		<Raster guid="718B8E7D-1F35-444E-B383-F48F2A6AC268" id="EXVEG1">
			<Name>Existing Vegetation</Name>
			<Path>01_Inputs/01_Ex_Veg/Ex_Veg_1/US_140EVT/us_140evt_Clip.tif</Path>
		</Raster>
		<Raster guid="792AA568-7298-4CF4-A2C4-EB9B35F27C97" id="HISTVEG1">
			<Name>Historic Vegetation</Name>
			<Path>01_Inputs/02_Hist_Veg/Hist_Veg_1/US_140BPS/us_140bps_Clip.tif</Path>
		</Raster>
		<Vector guid="B0A35A2F-FC4D-4994-8DF2-2A6288673939" id="NETWORK1">
			<Name>Segmented Network</Name>
			<Path>01_Inputs/03_Network/Network_1/NHD_24k_17060303_Perennial_500m.shp</Path>
		</Vector>
		<Vector guid="A313B1C9-3FCB-403B-9719-1AF8945B0C44" id="VALLEY1">
			<Name>Valley Bottom</Name>
			<Path>01_Inputs/04_Valley/Valley_1/17060303_Valley_Bottom_Edited.shp</Path>
		</Vector>
		<Vector guid="91B54CF4-D462-40C9-BF61-BD97F7AB6097" id="LRP1">
			<Name>Large River Polygon</Name>
			<Path>01_Inputs/05_LRP/LRP_1/NHD_Area.shp</Path>
		</Vector>
	</Inputs>
	<Realizations>
		<RVD dateCreated="2017-06-27 14:23:26" guid="76B24159-1F01-4537-9F9E-F6E82676DF72" id="RZ1" productVersion="1.0.8" promoted="True">
			<Name>RVD Realization 1</Name>
			<Inputs>
				<ExistingVegetation ref="EXVEG1">
					<ExistingCoverRasters>
						<Raster guid="50A07BE6-D1EA-4ABE-8BDF-F2C2B99F9B8D">
							<Name>Existing Riparian</Name>
							<Path>01_Inputs/01_Ex_Veg/Ex_Veg_1/Ex_Rasters/Ex_Riparian.tif</Path>
						</Raster>
						<Raster guid="C13FB28E-ADE0-48E8-BFA1-577A5426DE44">
							<Name>Existing Cover</Name>
							<Path>01_Inputs/01_Ex_Veg/Ex_Veg_1/Ex_Rasters/Ex_Cover.tif</Path>
						</Raster>
					</ExistingCoverRasters>
				</ExistingVegetation>
				<HistoricVegetation ref="HISTVEG1">
					<HistoricCoverRasters>
						<Raster guid="FF8BC95A-7753-48ED-BCF0-DDE3D10F9199">
							<Name>Historic Riparian</Name>
							<Path>01_Inputs/02_Hist_Veg/Hist_Veg_1/Hist_Rasters/Hist_Riparian.tif</Path>
						</Raster>
						<Raster guid="D3263E97-96C2-421B-8F9F-0019C895BC98">
							<Name>Historic Cover</Name>
							<Path>01_Inputs/02_Hist_Veg/Hist_Veg_1/Hist_Rasters/Hist_Cover.tif</Path>
						</Raster>
					</HistoricCoverRasters>
				</HistoricVegetation>
				<DrainageNetworks>
					<Network ref="NETWORK1">
						<ThiessenPolygons guid="6E9B077F-FAF4-4B28-99F9-90B13E61BC35">
							<Name>Thiessen Polygons</Name>
							<Path>01_Inputs/03_Network/Network_1/Thiessen/Thiessen_Valley.shp</Path>
						</ThiessenPolygons>
					</Network>
				</DrainageNetworks>
				<ValleyBottom ref="VALLEY1"/>
				<LargeRiverPolygon ref="LRP1"/>
			</Inputs>
			<Analyses>
				<Analysis>
					<Name>RVD Analysis</Name>
					<Outputs>
						<Vector guid="7BF8A702-F4AE-44F5-9D57-707188398011">
							<Name>RVD</Name>
							<Path>02_Analyses/Output_1/17060303_RVD.shp</Path>
						</Vector>
						<Raster guid="78A51A62-6298-4B81-9E7A-844DA24D2B2B">
							<Name>Conversion Raster</Name>
							<Path>02_Analyses/Output_1/Converstion_Raster.tif</Path>
						</Raster>
					</Outputs>
				</Analysis>
			</Analyses>
		</RVD>
	</Realizations>
</Project>

```

**Comment by wally-mac** [comment]
@Cashe93 I agree with Joe let's call this RCAT and include RVD, RVCT, and RCA and associated outputs. This is similar to how we handled BRAT, we didn't strip out individual components. sql and VBET will be a separate task to handle. I would prefer us focusing first on the most recent RCAT outputs such as upper Klamath. we'll discuss further a priority list.

**Comment by Cashe93** [comment]
@philipbaileynar, I am attempting to update a project.xml for an old RCA run similar to what I was doing for pyBRAT in #199. However, I am having trouble getting rid of all of the problems within studio code. Do you see any glaring issues in the screenshot posted below? Are there any changes that need to be made to the RCA.xsd?

![image](https://user-images.githubusercontent.com/49880208/129455748-94f45aca-cc9c-47aa-909a-8de13dc34549.png)

**Comment by philipbaileynar** [comment]
What's the error message when you hover over the red squiggle? The messages are normally very intuitive.

**Comment by Cashe93** [comment]
It says it expects an 'Existing Vegetation' node, but when I create one, it just pushes the same error down a couple of lines expecting something like 'Historic Vegetation' node, and so on. I've created the lines it expects to see, but then I'll still have errors. Perhaps the project XML is just missing data that I need to add? I'll be in the field for a few days, but I'll dive back into this when I return next week.
