### ISSUE TITLE
pyRCAT Curation 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#217]
## Specification
*Project Type*:  pyRCAT
*Layer(s)*: all 
*Type(s)* - Raster and Vector

## Description and/or Explanation of Need
Update project XML and Business Logic to support legacy RCA runs
-------
## To-Do 
- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend).
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by Cashe93** [comment]
@philipbaileynar, I am attempting to update a project.xml for an old RCA run similar to what I was doing for pyBRAT in #199. However, I am having trouble getting rid of all of the problems within studio code. Do you see any glaring issues in the screenshot posted below? Are there any changes that need to be made to the RCA.xsd?

![image](https://user-images.githubusercontent.com/49880208/129455748-94f45aca-cc9c-47aa-909a-8de13dc34549.png)

**Comment by Cashe93** [comment]
This is a repeat issue from #202
