### ISSUE TITLE
QRAVE Symbology for GUT Layers 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#232]
We have a functioning version of GUT layers in ArcRAVE

We have 18 GUT projects in Asotin (e.g. https://data.riverscapes.xyz/#/AsotinIMW/596f464d-768e-4198-a79a-9f760cdd6807)
![image](https://user-images.githubusercontent.com/9723905/130872063-0d882c59-f77f-4e4a-9e54-2d00dc093af5.png)

## Specification
*Project Type*:  `e.g. GUT` 
*Layer(s)*:
All GUT layers:
![image](https://user-images.githubusercontent.com/9723905/130872557-e55e8cd3-46a5-460c-83b2-2a0308cb30af.png)

*Type(s)* - Raster  and Vector

## Description and/or Explanation of Need
- [x] #233
- [x] We need to confirm that an GUT *.lyr files in shared that GUT uses in [shared](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/esri/Shared) are also in [shared](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/qgis/Shared) for QML

## Example(s) of Inspiration
Note, that annoyingly, we do not have hillshade in these projects and you have to load them from the CHaMP Surveys.

Tier 2 from ArcRAVe:
![image](https://user-images.githubusercontent.com/9723905/130872683-25f656f4-1059-4163-b4f8-ca97060ff006.png)

Tier 3 from ArcRAVE:
![image](https://user-images.githubusercontent.com/9723905/130872790-f29d6ae3-0759-498c-9128-7d6051e83b4e.png)

-------
## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. curation_QRAVE_GUT) 
- [x] See if  business logic needs any updates/changes (might not)
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] Delete local branch(es) you used for your pull request(s)
