### ISSUE TITLE
Symbology for D∞ Slope Analysis (percent)Layer in TauDEM Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#240]
## Specification
*Project Type*:  `TauDEM` 
*Layer(s)*:
D∞ Slope Analysis (percent)

*Type(s)* - Raster

## Description and/or Explanation of Need
Change color ramp to be consistent with other slopes (i.e. green low slope red high slope)

This came up during QC for: https://github.com/Riverscapes/RiverscapesData/issues/36
## Example(s) of Inspiration
Regular slope analysis

-------
## To-Do 
- [x] Start new branch with descriptive name for these changes
- [x] Author new `*.qml` for QRAVE of D∞ Slope Analysis and test in QRAVE and commit
- [x] Produce screen shot of D∞ Slope Analysis to provide in commit or later pull request for reviewer (include legend)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] Delete local branch(es) you used for your pull request(s)

**Comment by shelbysawyer** [comment]
Here is the updated D∞ Slope Analysis (percent) symbology:
<img width="799" alt="dinfflowdir_slp" src="https://user-images.githubusercontent.com/73311751/132782997-40b0f435-5371-4368-bd30-2e20538e128b.PNG">

**Comment by shelbysawyer** [comment]
Fixed in #251
