### ISSUE TITLE
Symbology for Hillshade Layer in ALL Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#243]
## Specification
*Project Type*:  All of our projects with BL that use hillshades
*Layer(s)*:
Hillsahde layers show up in all our tools 

*Type(s)* - Raster

## Description and/or Explanation of Need
In https://github.com/Riverscapes/riverscapes-tools/issues/252 we identified that Hillshades are too dark sometimes. 
We simply need to make a `hillshade.lyr` and `hillshade.qml` that force the stretching over the full range of 0 to 256. 

-------
## To-Do 
I

- [x] Start new branch with descriptive name for these changes (e.g. hillshade_Fix) 
- [x] Make  edits to every business logic file with a hillshade and add a `symbology="hillshade"` and commit to new branch 
- [x] Author `*.qml` for QRAVE cand test in QRAVE and commit
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of hillshade to `Shared`  and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Author symbology file for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by joewheaton** [comment]
@wally-mac please assign this to one of the curators as you see fit. This fixes the hillshade problems we had in Klamath. https://github.com/Riverscapes/riverscapes-tools/issues/252

**Comment by wally-mac** [comment]
@Tanmanfalcon can you please take on this task? Thanks

**Comment by joewheaton** [comment]
@philipbaileynar this is that hillshade one we were talking about.

**Comment by joewheaton** [comment]
@Tanmanfalcon and @Cashe93 can you give an update on this one please? I thought this might be done?

**Comment by Cashe93** [comment]
Any updates on this @Tanmanfalcon? If it hasn't been completed, this shouldn't take too long.

**Comment by Cashe93** [comment]
@joewheaton, I've just made a pull request with these changes.

**Comment by MattReimer** [comment]
I just merged that change.
