### ISSUE TITLE
Symbology for Velocity Raster Layer in Hydro Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#273]
## Specification
*Project Type*:  `Hydro` 
*Layer(s)*:
Velocity Magnitude 
*Type(s)* - Raster

## Description and/or Explanation of Need
Get going in WebRave and QRAVE

## Example(s) of Inspiration
![image](https://user-images.githubusercontent.com/9723905/134558079-a06ba1e7-d6fc-4135-9700-1c2c13072b70.png)

-------
## To-Do 
- [ ] Start new branch with descriptive name for these changes (e.g. curation_Hydro_Vel) 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by nick4rivers** [comment]
@joewheaton - if this is still needed can we reassign this to someone else that is more accustomed to these processes?

**Comment by CHafen** [comment]
@MattReimer I'm working on getting the hydro symbology working in Q. I have most of it, but the symbology isn't working properly for "Water Surface Elevation" and "WaterDepth (model vs surveyed)"
![Screenshot1](https://user-images.githubusercontent.com/39837888/225434194-73da5c38-f218-4e05-9d35-277a20debabf
.png)
This is what the default looks like for both the layers when I bring it into Q.
![Screenshot2](https://user-images.githubusercontent.com/39837888/225434539-6990992c-cc08-4f94-910a-0115509135d4.png)
Here's what the "Water Surface Elevation" looks like when I add the symbology I got from converting the "wsDEM.lyr" file to a .qml.
![Screenshot3](https://user-images.githubusercontent.com/39837888/225435122-ad3fd630-3b64-4707-b9ab-ec01c9ec3c47.png)
The "Water Depth (model vs surveyed)" doesn't show up at all with the symbology.
I tried a couple of different projects and they had the same problem.
I'm not sure if this is an issue with the layer or with how slyr converted the symbology from a .lyr to a .qml. All the other layers seem to have converted just fine though. But I have no idea how to fix this.

**Comment by MattReimer** [comment]
@CHafen without actually seeing the project and files it's hard for me to say what's going on. How are you converting the lyr files? What's your process? I'm having trouble understanding what "Working properly" means in this case. 

Just on a glance it seems lile the `Water Depth (Model vs surveyed)` symbology is showing up as discreet buckets instead of a smooth gradient so I'm assuming this is not intended. 

You may have to recreate the QML symbology by hand for these two cases.

**Comment by CHafen** [comment]
@MattReimer I figured out the problem for "Water Surface Elevation." The symbology wasn't adjusting to the elevation to the layer because it was set to user defined instead of min/max. 

For the Water Depth (Model vs surveyed), I think maybe the wrong file is getting pulled in. I don't have ArcMap though to check and see what it looks like in there, so I guess I need to find someone who can look at it in Arc and have them look into what's going on here for me.

**Comment by CHafen** [comment]
@wally-mac do you have a tech who is familiar with curation and has access to ArcMap I can work with to figure out what the problem with the symbology for the Water Depth (model vs surveyed) is in the Hyro model?

**Comment by MattReimer** [comment]
@CHafen glad you got some of this sorted. I think it's really important to have access to both a QGIS install (obviously and free) but also an Arc license. It's just too much guesswork otherwise. I'm sorry we don't have a better migration pathway in place but these two technologies are so different it made writing a decent convertor really hard.

**Comment by CHafen** [comment]
@Riverscapes/riverscape-project-curators would someone who has access to ArcMap be able to look into if the "Water Depth (model vs surveyed)" layer in the hydro model shows up in ArcMap. When I converted the layer file to a qml it didn't work. It looks like the file that's getting pulled in is a smooth gradient based on elevation, but the symbology is discreet buckets showing (I assume) difference between modeled and surveyed. So, I'm not sure if for some reason Q is just pulling in the wrong layer for this or why this problem exists. I don't have access to Arc though to see if it works there.

**Comment by leallysmith** [comment]
@CHafen I can take a look at this in arcmap, could you zip up the project and the .lyr file and so I can open it in arcmap? Or just point me to where I can download the file from!

**Comment by CHafen** [comment]
Thanks @leallysmith the link is [https://data.riverscapes.net/#/AsotinIMW](url) You can just download the first project on there and look at that one.

**Comment by CHafen** [comment]
Sorry @leallysmith, looks like that link didn't work...try just copy and pasting this https://data.riverscapes.net/#/AsotinIMW

**Comment by leallysmith** [comment]
Hey @CHafen I'm going to request access to the program and then I can take a look at this and the other issue you tagged me in.

**Comment by CHafen** [comment]
Thanks for looking at this @leallysmith.  This is showing all >1.30,  so I think it is actually the same in ArcAMap as Q, but for some reason the symbology still shows up for it in Arc, but not Q. The values you see in Q are elevation, which is why they're so high. So, Iooked through the Buisness Logic again and it looks like it's bringing in the same file for Water Depth (which uses elevation) as for Water Depth (modeled vs surveyed). So, I'll try to get that sorted out. Thanks for the help!
