### ISSUE TITLE
Symbology for Breaklines Layer in Topo Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#274]
## Specification
*Project Type*:  `Topo` 
*Layer(s)*:
Breaklines

*Type(s)* -  Vector

## Description and/or Explanation of Need
Lorem ipsum 

## Example(s) of Inspiration
![image](https://user-images.githubusercontent.com/9723905/134559146-fd9166d3-d80c-4540-a2d0-89b05fb08bb3.png)

-------
## To-Do 

- [ ] Start new branch with descriptive name for these changes (e.g. curation_Topo_Breaklines) 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by nick4rivers** [comment]
@joewheaton - can you assign this to someone else? I don't have the capacity to give this stuff the attention it needs if we wanna get QRiS moving.

**Comment by CHafen** [comment]
@MattReimer I'm not sure if you're the one to address these issues to, but if not maybe you can point me to who can fix them. 
1-In webRave Topo projects open but all the layers say "missing tiles" so nothing will display
![Screenshot1](https://user-images.githubusercontent.com/39837888/225427014-49180331-812e-4f34-9b4d-4fe104b36447.png)
2- I got most of the symbology for Topo working in Q on my computer. But I can't get the symbology for any of the "Hawkins Channel Units" and "Grain Size Occular Estimates" to work. This appears to be because the layer does not contain the attributes needed to symbolize these layers. I checked a couple of different projects and for all of them these layers were missing the needed attributes. 

![Screenshot2](https://user-images.githubusercontent.com/39837888/225428237-597d51f8-4ad3-4783-b040-021c87cce4f5.png)
This is just showing the "Tier 1" attribute table and you can see the legend in the layers panel, but the attribute table looks the same for all these layers (no Tier or Grain size included in it).

**Comment by MattReimer** [comment]
Let's ignore the WebRAVE problem for now. I'm just about to release a new version of the warehouse and I don't really have any time to support a product we're about to replace. If this issue shows up in the new version when it launches let's talk and get it fixed. 

As for the `Hawkins Channel Units`, if the original files are missing the columns we need to symbolize them I don't think there's much we can do. I'm not in the loop here so I may be missing something but this may be a case where we simply don't have enough information to succeed

**Comment by CHafen** [comment]
Alright, thanks @MattReimer

**Comment by CHafen** [comment]
Thanks @leallysmith. I'll just use the projects you linked to above for symbolizing for now, and I guess just some of the files are missing some data.
