### ISSUE TITLE
Add Valley Bottom, Road and Rail Inputs +Buffers as intermediates in pyBRAT and sqlBRAT to BL and Symbology for both

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#384]
## Problem
In the old layer package for BRAT, we showed the following:
### Inputs
- Inputs: Valley Bottom
- Inputs: Roads
- Inputs: Railroads

They are in the old pyBRAT projects but not the new sqlBRAT projects (example below from: [BRAT for HUC 10040204](https://data.riverscapes.xyz/#/BLM/4b53e516-946f-474a-8e19-24199cfd3401) )
![image](https://user-images.githubusercontent.com/9723905/142229365-3a10cab8-f35c-4931-805a-b1e5a1371739.png)

What does show up in old (example from Idaho BRAT 17040218):
![image](https://user-images.githubusercontent.com/9723905/142231106-b9a9e761-848e-4bf8-a062-77c639961291.png)

### Intermediates
- Intermediates: Streamside Buffer
- Intermediates: Vicinity Buffer
However, these are in both old pyBRAT BUT NOT in the new sqlBRAT @KellyMWhitehead and @philipbaileynar:

![image](https://user-images.githubusercontent.com/9723905/142230577-6175fd7d-bd03-45f0-9120-b96a4373567b.png)

They need to be because this is the only way you can judge the LANDFIRE data against the "Vegetation Suitability" classified rasters (0-4), which ironically only shows up in the sqlBRAT and not the pyBRAT!
![image](https://user-images.githubusercontent.com/9723905/142232065-12c935c3-a4e0-4ead-afa9-29415a88f04c.png)

## To-Do
For @philipbaileynar: 
- [ ] Please update sqlBRAT tool to add metadata tags to inputs to trace for sqlBRAT what project valley bottom, roads and rails came from.
- [ ] Please update sqlBRAT tool to write the buffer polygons to the intermediates.gpkg

For @wally-mac to assign and @jtgilbert to track:
- [ ] Add to sqlBRAT BL the missing "Anthropogenic" inputs to match pyBRAT (i.e. valley bottoms, railroads, roads, land use)
- [ ] Add to sqlBRAT BL the missing "Buffers" and fix symbology (too thick)
- [ ] Add to pyBRAT BL the missing "Vegetation Suitability" intermediates to match sqlBRAT
- [ ] Explore why Land Use Input in the pyBRAT is not displaying
- [ ] Confirm both sqlBRAT and pyBRAT are showing the same stuff in same order

**Comment by joewheaton** [comment]
Hello? @wally-mac, @Cashe93? Thoughts. Just brining to top of your notifications.

**Comment by Cashe93** [comment]
@joewheaton, apologies for the delayed response. I can take on the task of making the BL edits and getting sqlBRAT to be consistent with pyBRAT.  Should be pretty straight forward. I'll get crackin on this Monday.

**Comment by joewheaton** [comment]
No worries... thanks @Cashe93 sounds great.
