### ISSUE TITLE
Symbology for Restoration or Conservation Layer in BRAT Project Type

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/RiverscapesXML#414]
## Specification
*Project Type*:  BRAT
*Layer(s)*: Restoration or Conservation Opportunities
Layer Name (reference line in business logic if possible - e.g. : https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/BRAT.xml#L32

*Type(s)* - Vector

## Description and/or Explanation of Need
The colors used for the "straightforward" and "strategic" categories are too close/difficult to tell apart in maps:

![res_man_colors](https://user-images.githubusercontent.com/21687931/144483592-30ae9af3-606f-4e4d-b3e7-ca4cc3326333.png)

## Example(s) of Inspiration

-------
## To-Do 
Instructions for tasks: @joewheaton @Cashe93  and I discussed the need for this change. Assigning to @Cashe93  for now, can delegate as needed.
1. delete those tasks not needed; 
2. check off tasks as you complete them; 
3. do not close issue until all tasks completed
4. reference this issue in all commits (e.g. with `#33` notation where 33 is issue number)

- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by Cashe93** [comment]
Will this work for the updated symbology? 

![image](https://user-images.githubusercontent.com/49880208/147608251-f80e8fe5-a276-4d87-bf0b-6c694e0da2ef.png)

**Comment by jtgilbert** [comment]
@Cashe93 I think it looks good, much easier to distinguish now.

**Comment by Cashe93** [comment]
Right on. The updated symbology is part of pull request #434

**Comment by joewheaton** [comment]
Agreed, BUT, please make the easiest thickest line width, straight forward thicket than the others and then the rest at current thickness.
