### ISSUE TITLE
All Symbology for RIM Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#436]
## Specification
*Project Type*:  `e.g. [RIM](https://github.com/Riverscapes/RIM)` 
*Layer(s)*:
All

## Description and/or Explanation of Need
Consistent display across all three platforms.

-------
## To-Do 

- [ ] Start new branch with descriptive name for these changes (e.g. curation_RIM) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by CHafen** [comment]
@Jdgilby here's the curation stuff that needs to get done for RIM

**Comment by joewheaton** [comment]
@CHafen, @jtgilbert and @Jdgilby  thanks for this. Just a super minor housekeeping issue. When you do your pull requests, reference the issue they "address" or "fix" e.g. `addresses #436` so they show up in this ticket.  So when @jtgilbert did:
https://github.com/Riverscapes/RiverscapesXML/pull/438, he could have mentioned this issue there or in the commit: https://github.com/Riverscapes/RiverscapesXML/pull/438/commits/1b904cdc221e95428dd7656c077236f73ca13d12

To show how this shows up above when this is done, I've added those references to both. It is not mission critical, but it makes life easier when you're trying to track down what was done.

**Comment by CHafen** [comment]
@Jdgilby I updated the Inundation business logic so it will use the symbology that is already in the shared folders (BRAT existing cap, VBET, DEM and hillshade). It seems to work in Q just fine, but the hillshade and dem don't appear to be working in WebRave. When you have a chance would you mind taking a look to see if you can see why it might not be working?

**Comment by CHafen** [comment]
@joewheaton this is basically done other than a few issues as described in issue #448 and #451.
