### ISSUE TITLE
Update ArcRAVE & WebRAVE Symbology for VBET Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#500]
## Specification
*Project Type*:  `VBET` 

## What we Need
We have everything working (for now) like we want in QRAVE from #474 and #499. This ticket is just about getting same stuff working in WebRAVE and ArcRAVE. @wally-mac it would be super helpful to get this done before Christmas or New Year if possible, but if no one is available, that is fine. Let me know and reassign as you see fit. 

-------
## To-Do 

- [ ] Start new branch with descriptive name for these changes (e.g. VBET_WebArc) 
- [ ] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

FYI @shelbysawyer (please provide support to @wally-mac and curator(s) as needed.

**Comment by joewheaton** [comment]
@wally-mac any update on this one?

**Comment by joewheaton** [comment]
@shelbysawyer, please take this one over.

**Comment by shelbysawyer** [comment]
Curation tasks for VBET projects in the new warehouse can be tracked in #582. Closing this.
