### ISSUE TITLE
Symbology for all Layers in GNAT Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#503]
@lauren-herbine lets get what is in GNAT looking decent. 

## Specification
*Project Type*:  `GNAT` 
*Layer(s)*:
All

Make sure to go through and expose all the IGOs by each metric! 

*Type(s)* - Raster or Vector

## Description and/or Explanation of Need
We need to be able to quickly interrogate results in WebRV and QRV

## Example(s) of Inspiration
See VBET IGO Moving Window Metrics
-------
## To-Do 

- [ ] Start new branch with descriptive name for these changes 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)
