### ISSUE TITLE
Symbology updates for New Layers in new Warehouse 2.0 Riverscapes Context Project Type

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#545]
@wally-mac please assign as appropriate. This is a HIGH priority. 

## Specification
*Project Type*:  `Riverscapes Context` 
*Layer(s)*:
- [ ] Roads (not even showing in webRAVE) 
- [ ] Rail (not even showing in webRAVE)
- [ ] NHD Flowlines Segmented 300 m (add small filled circles that display at more zoomed in zoom levels to depict segment ends)
- [ ] NHD Flowlines intersected with road, rail and ownership (add small filled circles that display at more zoomed in zoom levels to depict segment ends)
- [ ] Network Upstream Drainage Area (not showing correctly in webRAVE)
- [ ] Ecoregions 1- 4 are NOT symbolized at all or correctly (use EPAs legends to get colors and labels).
- [ ] Geology - _maybe symbolize based on `MAJOR1` and add label based on `ORIG_LABEL`; look at documentation for color choices and fill, but make transparent so it can be seen over hillshade and AP_
- [ ] State Boundaries - _Fairly bold solid black line, and add label._
- [ ] County Boundaries - _Similar to state, but less prominent. Make sure label is present_
- [ ] LANDIFIRE - None of the new layers got symbology! They all need it based on defaults in LANDFIRE 
  - [ ] Veg Cover - EVC 
  - [ ] Veg Height- EVH
  - [ ] Historic Disturbance - HDst
  - [ ] Fuel Disturbance - FDst
  - [ ] Fuel Characteristic Classification - FCCS
  - [ ] Vegetation Condition
  - [ ] Vegetation Departure
  - [ ] Succession Classes

*Type(s)* - Raster and Vector

## Description and/or Explanation of Need
A bunch of changes were made to RS_Context and now that those are getting re-run, we need symbology updated and fixed across all three platforms.  
- [ ] Update all label fonts to new Karla font series (also play with 
- [ ] Add more labels to more layers show at specified zoom levels and make work in WebRV
  - [ ] Add labels of stream names to Perennial Drainage Network & Intermittent
  - [ ] Add Lakes, Ponds, Reservoir Name label for high zoom levels
  - [ ] Turn Watershed HUC names for 12, 10, 8, 6, 4 and 2 to be two lines. First line HUC (e.g. `160102`) and second line the name (e.g. 'Lower Bear`). 
  - [ ] Add labels for States
  - [ ] Add Labels for Counties
- [ ] Figure out how to get WebRV to not show two labels for same feature 

Fix Legends on:
- [ ] All PRISM Temperature class labels in WebRV
- [ ] All new LANDFIRE classes
- [ ] Ecoregions 1 - 4
- [ ] 
## Example(s) of Inspiration
Please go to raw sources of data for Geology, LANDFIRE and EcoRegions for cartographic specification (don't invent your own if not needed).

Here is a [Riverscapes Context for HUC 1601020204](https://staging.warehouse.riverscapes.net/rv/d16a225e-55b0-41b2-9519-507db79cb7f9) project to play with in new warehosue. 

-------
## To-Do 

- [ ] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by wally-mac** [comment]
@leallysmith I'm assigning this to you. Please delegate as needed. Thanks.

**Comment by shelbysawyer** [comment]
@leallysmith There's a good chance that some of the tickets I've added are known issues, but I just wanted to throw them here in case they're not. Feel free to close or ask for more info on any of them. Thanks!
