### ISSUE TITLE
Roads (not even showing in webRAVE)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#553]
This one may be a symbology curation issue, or it may be something in WebRV needing @MattReimer help.

## To-Do 
- [ ] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by MattReimer** [comment]
Roads show up in QRave but not at all on the map. This one could very well be a tiling issue but I won't know until I dig in.

**Comment by Cashe93** [comment]
Likely, not super helpful, but this layer has been curated and was working at some point. 

Symbology/web/Shared/roads.json

**Comment by MattReimer** [comment]
Yeah, the tilerizer is pretty sensitive to bad geometry so things like self intersections, empty polygons etc can freak it out.
