### ISSUE TITLE
NHD Flowlines Segmented 300 m (add small filled circles that display at more zoomed in zoom levels to depict segment ends)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#555]
Lets make these more appealing. 

## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] Author or Update any project type documentation
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by wally-mac** [comment]
@leallysmith I'm assigning this to you. Please delegate as needed. Thanks.

**Comment by joewheaton** [comment]
> @leallysmith I'm assigning this to you. Please delegate as needed. Thanks.

@wally-mac, just a reminder, you change the Assignees....

**Comment by Cashe93** [comment]
![image](https://user-images.githubusercontent.com/49880208/236917632-88f8917a-c1c8-4f07-9cf7-232b4c71427b.png)
![NHD_segments](https://user-images.githubusercontent.com/49880208/236917887-92e65a17-5dc9-4baa-9f95-01d0b144e88a.gif)
