### ISSUE TITLE
NHD Flowlines intersected with road, rail and ownership (add small filled circles that display at more zoomed in zoom levels to depict segment ends)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#556]
Lets make these more appealing.  Can be same as #555, but note difference of view below.

## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] Author or Update any project type documentation
- [x] Add Project Views with this layer, road, rail and ownership on it to highlight how it works. 
- [x] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [x] After pull request(s) merged, test in updated WebRAVE
- [x] Delete local branch(es) you used for your pull request(s)

**Comment by joewheaton** [comment]
See https://youtu.be/Ze60sYAgu9s?t=1065

**Comment by wally-mac** [comment]
@leallysmith I'm assigning this to you. Please delegate as needed. Thanks.

**Comment by Cashe93** [comment]
![image](https://user-images.githubusercontent.com/49880208/236929155-4e3a997f-6ffe-4c75-a18e-ba8501fe3247.png)

![NHD_segments](https://user-images.githubusercontent.com/49880208/236931415-dd1f7458-abdc-49c5-8dad-042431caeaa2.gif)

## Difference in segmented symbology 

![image](https://user-images.githubusercontent.com/49880208/236932400-594e933e-4629-4c4b-8a7b-bc1798b9415f.png)
