### ISSUE TITLE
Network Upstream Drainage Area (not showing correctly in webRAVE)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#557]
This was noticed in https://github.com/Riverscapes/riverscapes-tools/issues/743 on [501000301](https://warehouse.riverscapes.net/p/fc212b46-4ab1-401d-a6f7-71681883a956/) but not in [701010102](https://warehouse.riverscapes.net/p/50bc33c0-671a-4f93-b9d9-a6dc8211a610/). So inconsistent. Not sure yet... Flagging @philipbaileynar and @MattReimer first. 

However, worked fine in https://warehouse.riverscapes.net/rv/50bc33c0-671a-4f93-b9d9-a6dc8211a610
## To-Do 

- [ ] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by joewheaton** [comment]
Well, it didn't work the first time, but I reloaded it and could not reproduce it! Not sure what was going on? Closing for now.
