### ISSUE TITLE
State Boundaries - Fairly bold solid black line, and add label.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#559]
Thicker (then county) solid hollow black state border line.  Use Jeb Brains Mon for new font (see #562 )
## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] Author or Update any project type documentation
- [x] Update or Add Project Views to Reflect Changes (if necc.)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] After pull request(s) merged, test in updated ArcRAVE
- [x] After pull request(s) merged, test in updated WebRAVE
- [x] Delete local branch(es) you used for your pull request(s)

**Comment by Cashe93** [comment]
State labels not showing up. Mentioned in https://github.com/Riverscapes/RiverscapesXML/issues/560#issuecomment-1538782685

**Comment by Cashe93** [comment]
Labels now showing up. Closing this issue.
