### ISSUE TITLE
County Boundaries - Similar to state, but less prominent. Make sure label is present

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#560]
Thinner (than State) solid hollow black state border line. Use Jet Brains Mono for new font (see https://github.com/Riverscapes/RiverscapesXML/discussions/562 )

## To-Do 

- [x] Start new branch with descriptive name for these changes (e.g. RS_Context 2.0) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [x] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [x] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [x] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [x] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] Author or Update any project type documentation
- [x] Update or Add Project Views to Reflect Changes (if necc.)
- [x] After pull request(s) merged, test in updated qRAVE
- [x] After pull request(s) merged, test in updated ArcRAVE
- [x] After pull request(s) merged, test in updated WebRAVE
- [x] Delete local branch(es) you used for your pull request(s)

**Comment by wally-mac** [comment]
@leallysmith  I'm assigning this to you. Please delegate as needed. Thanks.

**Comment by Cashe93** [comment]
Making this pull request: #594 

![image](https://user-images.githubusercontent.com/49880208/234108727-bede50b3-b35e-434d-ab81-dc58c8fb93a2.png)

**Comment by Cashe93** [comment]
A couple of issues with the web symbology: 
1. Labels are not showing up 
2. State labels might be redundant since base imagery already has the state labeled. @joewheaton should we still keep this? 

![image](https://user-images.githubusercontent.com/49880208/236893705-c862405a-5cbf-48e2-aeb2-f59f837f5aca.png)

@jtgilbert any suggestions on getting the labels to show? 

Project: https://staging.warehouse.riverscapes.net/p/98e12ba5-2233-4205-86a4-201c9bfae4bc/
Symbology location: RiverscapesXML\Symbology\web\RSContext\counties.json and/or states.json

**Comment by Cashe93** [comment]
Labels now showing up. Closing this issue.
