### ISSUE TITLE
Symbology for Condition Layers in RCAT Project Type

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/RiverscapesXML#650]
## Specification
*Project Type*:  `RCAT` 
*Layer(s)*: both vwReaches and vwIgos
Layer Name: Riparian Condition

*Type(s)* - Vector

## Description and/or Explanation of Need
I think we should update the color scheme for condition (to make it distinct from other layers that use the red to green color scheme) to match the old version of the tool.

## Example(s) of Inspiration
 Example [here](https://rcat.riverscapes.net/assets/images/hr/RCA_Bar_chart_10_16.png) (don't worry about the old confined categories)

-------
## To-Do 
Instructions for tasks:
1. delete those tasks not needed; 
2. check off tasks as you complete them; 
3. do not close issue until all tasks completed
4. reference this issue in all commits (e.g. with `#33` notation where 33 is issue number)

- [x] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [x] Make necessary edits to business logic and commit to new branch 
- [x] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [x] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [x] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit  
- [ ] Make pull request for just ArcRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated ArcRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by jtgilbert** [comment]
Instead of a new issue I'm going to tag on this one @emilySarge .
We also need to add intermediates related to riparian conversions. The vwReaches and vwIgos layers have a field `ConversionType` that should have symbology curated. My preference would be to use [this](https://rcat.riverscapes.net/assets/images/hr/RVCT_Bar_chart_10_16.png) color scheme, but with different lightness/darknesses of the colors based on the level of conversion (%). I think it would also be useful to UPDATE the conversion raster to use this same color scheme. 
Finally, business logic will need updated to included these intermediates. 
This is kind of a lot, so reach out when/if you need some guidance or have questions.

**Comment by emilySarge** [comment]
Sounds good!

**Comment by emilySarge** [comment]
@jtgilbert Just to be clear, this is the color change you're aiming for?
![image](https://github.com/Riverscapes/RiverscapesXML/assets/102846029/c32599ec-664a-4389-a45c-0dd62d276bac)

**Comment by jtgilbert** [comment]
Yes @emilySarge, looking good.

**Comment by emilySarge** [comment]
IGO sizing options:
![image](https://github.com/Riverscapes/RiverscapesXML/assets/102846029/1f08830b-2c0c-4d55-bbee-a95c335b4335)

**Comment by emilySarge** [comment]
Hey @jtgilbert, did you see the 'RCAT Condition Symbology Updates' pull request that I made on 12 Sept? It has the new esri files and edits to the qgis files.

**Comment by MattReimer** [comment]
@emilySarge you can use hex values too or rgb if that works better for you:

- `rgb(0,255,0)`
- `#00FF00`

**Comment by jtgilbert** [comment]
@emilySarge I'm not seeing any open PRs. I may have already merged it?

**Comment by joewheaton** [comment]
@jtgilbert, @emilySarge and @dominique-shore. This has become a high priority to get the IGO Riparian Condition and and Reach Riparian Condition working in Web Rave. I have assigned this to @dominique-shore for now. It looks like @emilySarge might have already done the work here, but we never got any resolution on the pull-requests. If those commits are on a branch that someone can find, lets review them and action them. 

See: https://riverscapes.freshdesk.com/a/tickets/18 and https://riverscapes.freshdesk.com/a/tickets/26

**Comment by dominique-shore** [comment]
@jtgilbert committed on Sept to change the vwIGOs from "condition_igo" to "condition_igo_v2" and vwReaches from "condition" to "condition_v2". Those .qml files are present in symbology/qgis/RCAT, but not sybmology/web/RCAT. The new .qml files just need to be added to the web folder. 

HOWEVER - When I add the RCAT .xml files in QRAVE, and add the vwIGOs, nothing appears and there is no Layer Metadata. I'm not sure why that is happening.

**Comment by dominique-shore** [comment]
The FPAccess.qml file is also missing in sybmology/web/RCAT, so intermediates/floodplain accessibility is loading without symbology in WebRAVE

**Comment by jtgilbert** [comment]
@emilySarge will you have time in the next little bit to update web symbology, or should we get someone else on it?

**Comment by jtgilbert** [comment]
@dominique-shore `HOWEVER - When I add the RCAT .xml files in QRAVE, and add the vwIGOs, nothing appears and there is no Layer Metadata. I'm not sure why that is happening. The data exists because if I add the rcat.gpkg, I can add the vwIgos layer and apply the condition_igo_v2.qml, and it looks good.`
I think this is a viewer bug we need to file. I've noticed this as well, it won't let me add line network outputs and igo outputs at the same time I have to remove the whole outputs folder then add one or the other.

**Comment by dominique-shore** [comment]
Yep - I'm seeing the same thing, now. I can look at one or the other, but not both. @jtgilbert  Do you want to file the QRAVE issue or should I?

**Comment by jtgilbert** [comment]
> Yep - I'm seeing the same thing, now. I can look at one or the other, but not both. @jtgilbert Do you want to file the QRAVE issue or should I?

Go for it!

**Comment by dominique-shore** [comment]
> Go for it!

https://github.com/Riverscapes/QRAVEPlugin/issues/95

**Comment by dominique-shore** [comment]
@jtgilbert  I'm working on symbology for the field `ConversionType`, and came across a couple things. 

1. In the layer `vwReaches`, the value Conifer - Significant (>50%). It's present in 'vwIgos'
2. Not sure what Grass/Shrubland vs. From Grass/Shrubland. I would assume that Grass/Shrubland is supposed to change to Grass&Shrubland, but I'm not sure where from grass/shrubland falls, as many of types are probably conversion from grass/shrubland. Would an area that was changed from shrubland to a development show up as 'From Grass/Shrubland' or 'Development?' 


![image](https://github.com/Riverscapes/RiverscapesXML/assets/106760640/cd7e610d-7f8e-4b5b-98bd-81c4b74f3342)

**Comment by jtgilbert** [comment]
@dominique-shore there's a way to add classes for which there's not values in the dataset you're using. I can show you tomorrow if you have any time to meet for a min.

**Comment by dominique-shore** [comment]
@jtgilbert Here are the labels and colors I have for <ConditionType>. Some are based off the colors you selected and a few I made up, as those classes didn't exist in the past version of RCAT. Ones I created are in italic. Let me know what you think. 

![image](https://github.com/Riverscapes/RiverscapesXML/assets/106760640/8acba852-ad43-40be-b59f-3b1a93304e15)

**Comment by jtgilbert** [comment]
@dominique-shore Maybe try making the FROM ones just really light (or really dark) shades of their counterparts. Right now I could see confusing from conifer and no change and from and grass and to grass.

**Comment by dominique-shore** [comment]
Sure - those are close. I'll make them lighter versions.

**Comment by dominique-shore** [comment]
@jtgilbert After testing the ConditionCode symbology in QRAVE, the vector files both look good, but the raster file does not. The `Condition` raster displays with singleband gray symbology, like a hillshade. I check the spelling of the raster .qml in the business logic & that looks fine. 

I'm just having issues with that .qml in general. I changed the colors to match the vector files, and it looked good. However, whenever I just use 'load style' to add the .qml to a condition raster, it looks completely different, and the colors are wrong. The colors and classification look fine in the legend & under properties -> symbology, but do not look right on the map.  I'm stumped. 

![image](https://github.com/Riverscapes/RiverscapesXML/assets/106760640/c6db4667-3847-4bac-be8c-02031af63cf4)
