### ISSUE TITLE
Business logic and QMLs for RME

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#664]
## Specification
*Project Type*:  RME
*Layer(s)*: all

## Description and/or Explanation of Need
RME basic business logic and symbology in Q

## Example(s) of Inspiration
Optional: Drag and paste in here any examples or screen shots of what you want this to look like 

-------
## To-Do for each layer

- Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- Make necessary edits to business logic and commit to new branch 
- Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- Author or Update any project type documentation
- Update or Add Project Views to Reflect Changes (if necc.)
- After pull request(s) merged, test in updated qRAVE
- Delete local branch(es) you used for your pull request(s)

Layers:

- [ ] Primary Channel Gradient
- [ ] Valley Bottom Gradient
- [ ] Stream Order
- [ ] Headwater
- [ ] Stream Type
- [ ] Estimated Low-Lying Valley Bottom
- [ ] Estimated Low-Lying Valley Bottom (DGO)
- [ ] Active Channel Area
- [ ] Active Channel Area (DGO)
- [ ] Integrated Width
- [ ] Active Channel Ratio
- [ ] Active Channel Ratio (DGO)
- [ ] Relative Flow Length
- [ ] Stream Size Metric
- [ ] Confluence Count
- [ ] Diffluence Count
- [ ] IGO Planform Sinuosity of main LevelPath
- [ ] Drainage Area
- [ ] Ecoregion IV
- [ ] Low-Lying Valley Bottom Proportion
- [ ] Confinement
- [ ] Constriction Ratio
- [ ] Length of Confining Margins
- [ ] Tributary Junction Count per stream km
- [ ] Tributary Junction Count (DGO)
- [ ] Road Density
- [ ] Road Density (DGO)
- [ ] Rail Density
- [ ] Rail Density (DGO)
- [ ] Land Use Intensity
- [ ] Land Use Intensity (DGO)
- [ ] Floodplain Accessibility
