### ISSUE TITLE
Symbology Anthro Project Type

### ISSUE THREAD

**Issue by dominique-shore** [Riverscapes/RiverscapesXML#665]
## Specification
*Project Type*:  `Anthro` 
*Layer(s)*:

https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/V2/Anthro.xml

Outputs/IGO Outputs
- Railroad Length (Vector) L14
- Railroad Density (Vector) L15
- Canal Length (Vector) L16
- Canal Density (Vector) L17
- Road Crossing Count (Vector) L18
- Road Crossing Density (Vector) L19
- Diversion Point Count (Vector) L20
- Diversion Point Density (Vector) L21
Intermediates
- Land Use Intensity Raster (Raster) L42
- Railroads with the Valley Bottom (Vector) L46
- Roads with the Valley Bottom (Vector) L47
Inputs
- Roads (Vector) L63

## Description and/or Explanation of Need
- **Outputs/IGO Outputs** No 'values' are being symbolized with the IGOs listed above. All points are mapped with the same color, which is the minimum color in the color scheme.   For example, the lowest class for canal density is <0.001, which is mapped as darker blue. All points map with the dark blue color. 
- **Intermediates/Land Use Intensity Raster** tiling issue, not displaying in WebRave
- **Intermediates/Railroads with the Valley Bottom** no appearing in QRAVE
- **Intermediates/Roads with the Valley Bottom** The layer looks very segmented is not displaying correctly in WebRave or QRave 
- **Inputs/Roads** Layer not appearing in WebRave or QRAVE

### On railroads (and probably roads)
I originally started in a drainage that did not have railroad and noticed a couple things. In Outputs/Reach Outputs, in WebRave the symbology is just black, and in QRAVE, nothing appears. It would make most sense for all the streams to have the >1km/Not Close symbology. 

I believe the issue is that when there is no railway in the valley bottom, no Intermediates/Railroads with the Valley Bottom layer exists, so the Output polylines are not created. 

-------
## To-Do 
Instructions for tasks:
1. delete those tasks not needed; 
2. check off tasks as you complete them; 
3. do not close issue until all tasks completed
4. reference this issue in all commits (e.g. with `#33` notation where 33 is issue number)

- [ ] Start new branch with descriptive name for these changes (e.g. curation_Veg_RCAT) 
- [ ] Make necessary edits to business logic and commit to new branch 
- [ ] Author `*.qml` for QRAVE of layer(s) and test in QRAVE and commit
- [ ] Produce screen shot of each qml layer to provide in commit or later pull request for reviewer (include legend). Also, provide warehouse link to riverscape project you did testing on (use same project(s) for testing ArcRAVE and WebRAVE)
- [ ] Make pull request for just QRAVE changes. Choose appropriate reviewer(s)
- [ ] Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)
- [ ] Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on
- [ ] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [ ] Author or Update any project type documentation
- [ ] Update or Add Project Views to Reflect Changes (if necc.)
- [ ] After pull request(s) merged, test in updated qRAVE
- [ ] After pull request(s) merged, test in updated WebRAVE
- [ ] Delete local branch(es) you used for your pull request(s)

**Comment by dominique-shore** [comment]
@jtgilbert I tried to do my best to summarize the issues with Anthro symbology. Sorry I'm not much help next week.
